spring.datasource.url=jdbc:mysql://db4free.net:3306/springmyfirst
spring.datasource.username=mugeshroot
spring.datasource.password=mugesh2004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true